### ISSUE TITLE
Firmware 7

### ISSUE THREAD

**Issue by BenouGui** [grzegorz914/homebridge-enphase-envoy#65]
I have a problem witch firmware 7 
[11/12/2022, 19:31:34] [homebridge-enphase-envoy] Device: 192.168.1.6 Envoy-S, inventory error: AxiosError: Request failed with status code 401, reconnect in 15s.

**Comment by BenouGui** [comment]
[homebridge.log-4.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202973/homebridge.log-4.txt)

**Comment by grzegorz914** [comment]
Please generate new Token here https://enlighten.enphaseenergy.com/entrez-auth-token?serial_num={} and ad it to the plugin Config and let me know.

**Comment by BenouGui** [comment]
Same problem

**Comment by grzegorz914** [comment]
Are you sure you have paste only the data after Token: without apostrophe

**Comment by BenouGui** [comment]
![4FEAF9A2-79C0-4589-B5F3-D6F58D88D3F4](https://user-images.githubusercontent.com/72623517/206925903-32f47129-65a5-4256-b1f6-dc830b80ca63.png)
![B38CDE0F-5293-44F6-90B3-C649178A0BC1](https://user-images.githubusercontent.com/72623517/206925905-dc103eed-eabf-44d6-81f4-0e2bc2a288db.png)
 
 yes sure

**Comment by grzegorz914** [comment]
Here https://github.com/grzegorz914/homebridge-enphase-envoy/issues/63#issuecomment-1345527583  by test was same problem but was fixed after generate new token.

**Comment by BenouGui** [comment]
Dont work for me :/

**Comment by grzegorz914** [comment]
can you try 6.0.1-beta.0 and let me know

**Comment by BenouGui** [comment]
[homebridge.log-8.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10209691/homebridge.log-8.txt)
I retested to hand over my token via both:
https://enlighten.enphaseenergy.com/entrez-auth-token?serial_num=12224xxxxx
and 
https://entrez.enphaseenergy.com

But still the same error

**Comment by BenouGui** [comment]
The on/off of the gateway did not change anything, on the internet I see a lot of people using session cookies.
When I try to curl
curl -f -k -H 'Authorization: Bearer TOKENTOKENTOEKN' -X GET https://192.168.1.6/api/v1/production/inverters
curl: (22) The requested URL returned error: 401 Unauthorized
But 
curl -f -k -H 'Authorization: Bearer TOKENTOKENTOEKN' -X GET https://192.168.1.6/api/v1/production/
-- > {
  "wattHoursToday": 0,
  "wattHoursSevenDays": 21534,
  "wattHoursLifetime": 21529,
  "wattsNow": 8
}
But in the web Gui after login witch token. 
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/72623517/207256489-20712cbf-501a-4145-9cb0-ef6d35552235.png">

**Comment by grzegorz914** [comment]
can you try with CURL this: curl -f -k -H 'Authorization: Bearer TOKENTOKENTOEKN' -X GET https://inventory.json

and let me know the output

**Comment by grzegorz914** [comment]
beta.2 enabled cookies, try again please

**Comment by BenouGui** [comment]
pi@homebridge:~ $ curl -f -k -H 'Authorization: Bearer TOKENTOKEN' -X GET https://192.168.1.6/inventory.json
curl: (22) The requested URL returned error: 401 Unauthorized.

**Comment by BenouGui** [comment]
After login witch token in the web Gui 
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/72623517/207261065-d575e40e-2786-4c30-abb8-9bc41abd0885.png">

For the beta 2 the same error

**Comment by BenouGui** [comment]
look here https://github.com/edasque/enphaseLocalToInfluxDB#authorization-flow

**Comment by grzegorz914** [comment]
looks like some bug in envoy firmware, I pushed beta.3 to test, here skipped the inventory data, try it and post the log please

**Comment by grzegorz914** [comment]
ups try beta.4

**Comment by BenouGui** [comment]
[homebridge.log-10.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10215850/homebridge.log-10.txt)

**Comment by grzegorz914** [comment]
arę you try beta.4

**Comment by BenouGui** [comment]
yes at the bottom of the log it's beta 4

**Comment by BenouGui** [comment]
[homebridge.log-11.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10215906/homebridge.log-11.txt)


[13/12/2022, 09:32:27] [homebridge-enphase-envoy] Device: 192.168.1.6 Envoy-Ss, debug production: {
  "wattHoursToday": 149,
  "wattHoursSevenDays": 21534,
  "wattHoursLifetime": 21675,
  "wattsNow": 520
}
[13/12/2022, 09:32:27] [homebridge-enphase-envoy] Device: 192.168.1.6 Envoy-Ss, production ct error: AxiosError: Request failed with status code 401, reconnect in 15s.

**Comment by BenouGui** [comment]
[Uploading homebridge.log-12.txt…]()

**Comment by BenouGui** [comment]
[Uploading homebridge.log-13.txt…]()

**Comment by grzegorz914** [comment]
ok, try beta.8 and get me the log, I have added some debug to the response

**Comment by grzegorz914** [comment]
beta.9 ready

**Comment by BenouGui** [comment]
[homebridge.log-15.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10216699/homebridge.log-15.txt)

**Comment by grzegorz914** [comment]
try beta.10

**Comment by BenouGui** [comment]
[homebridge.log-16.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10217270/homebridge.log-16.txt)

**Comment by grzegorz914** [comment]
beta.11 ready

**Comment by BenouGui** [comment]
[homebridge.log-17.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10217321/homebridge.log-17.txt)

**Comment by grzegorz914** [comment]
try beta.12

**Comment by BenouGui** [comment]
[homebridge.log-18.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10217340/homebridge.log-18.txt)

**Comment by BenouGui** [comment]
[homebridge.log-19.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10219630/homebridge.log-19.txt)
beta 20

**Comment by grzegorz914** [comment]
beta.21

**Comment by BenouGui** [comment]
[homebridge.log-20.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10219788/homebridge.log-20.txt)
Beta 21

**Comment by grzegorz914** [comment]
try 22

**Comment by grzegorz914** [comment]
try 23

**Comment by BenouGui** [comment]
[homebridge.log-22.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10219951/homebridge.log-22.txt)
beta 23

**Comment by grzegorz914** [comment]
24

**Comment by BenouGui** [comment]
[homebridge.log-23.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10219984/homebridge.log-23.txt)
beta 24

**Comment by grzegorz914** [comment]
25

**Comment by BenouGui** [comment]
[homebridge.log-24.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10220151/homebridge.log-24.txt)

**Comment by BenouGui** [comment]
[homebridge.log-25.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10220223/homebridge.log-25.txt)

https://github.com/H4nsie/EnphaseEnvoy

**Comment by grzegorz914** [comment]
it working 28

**Comment by BenouGui** [comment]
[homebridge.log-26.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10220277/homebridge.log-26.txt)

yes it seems to work, what was the problem?

**Comment by grzegorz914** [comment]
try 29 too, need to pas cookies after check jet and set instance

**Comment by BenouGui** [comment]
[homebridge.log-27.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10220305/homebridge.log-27.txt)

**Comment by grzegorz914** [comment]
nice, thanks for test

**Comment by NoSnow3** [comment]
Sorry been AFK.

We all good now?

**Comment by NoSnow3** [comment]
[Homebridge 6.0.1 Beta 30.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10221406/Homebridge.6.0.1.Beta.30.txt)


As Requested

**Comment by grzegorz914** [comment]
please again 31

**Comment by NoSnow3** [comment]
[homebridge 6.0.1 Beta 31.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10221466/homebridge.6.0.1.Beta.31.txt)

"Envoy-S, power mode error: AxiosError: Request failed with status code 401, reconnect in 15s."

**Comment by grzegorz914** [comment]
again 32

**Comment by NoSnow3** [comment]
[homebridge 6.0.1 Beta 32.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10221505/homebridge.6.0.1.Beta.32.txt)

Nothing spotted

**Comment by grzegorz914** [comment]
OK ready for release

Thanks

**Comment by grzegorz914** [comment]
v6.0.1 released
